### ISSUE TITLE
Parameter to get___s() functions in the PHP API is incorrectly referenced

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-sdk#1]
As seen here:

![image](https://cloud.githubusercontent.com/assets/17009372/12723654/56b9f2c4-c8d8-11e5-8f3c-19056a4fa807.png)

`$queryParemeters` is referenced as a constant in the **APIHelper::appendUrlWithQueryParameters** call.  This is present in `getSectors()` in the **SectorController** as well as other similar functions from other controllers (`getUsers()`, `getNodes()`, etc.).

**Comment by tarkal** [comment]
Resolved by @Kartik in the APIMatic core
